server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topic: order-created-topic
